openapi: 3.0.0
info:
  title: 'My First API'
  version: '0.1'
paths:
  /examples:
    get:
      operationId: 087bdd2163dba93152a008cb367b49e8
      responses:
        '200':
          description: 'An example resource'
