<?php
use PHPUnit\Framework\TestCase;
use Gvera\Services\TwigService;
use Gvera\Helpers\config\Config;
class TwigServiceTest extends TestCase
{

    private $service;

    public function setUp():void
    {
        $this->service = new TwigService($this->getMockedConfig());
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function testNeedsTwig()
    {

        $needsTwig = $this->service->needsTwig('Test', 'index', __DIR__ . '/../../tests/Views/');
        $this->assertTrue($needsTwig);
        $this->service->reset();
        $doesntNeedTwig = $this->service->needsTwig('Test', 'index');
        $this->assertFalse($doesntNeedTwig);
    }

    /**
     * @test
     */
    public function testLoadTwig()
    {
        $env = $this->service->loadTwig(__DIR__ . '/../../tests/Views/');
        $this->assertNotNull($env);
    }

    private function getMockedConfig()
    {
        $config = $this->createMock(Config::class);
        return $config;
    }
}