<?php

class UserServiceTest extends \PHPUnit\Framework\TestCase
{

    private $us;
    /**
     * @test
     */
    public function validateEmail()
    {
        $invalidEmail = 'test';
        $this->assertFalse($this->us->validateEmail($invalidEmail));
        $validEmail = 'test@test.com';
        $this->assertTrue($this->us->validateEmail($validEmail));
    }

    public function setUp()
    {
        $this->us = new \Gvera\Services\UserService();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function generateAndValidatePassword()
    {
        $passHash = $this->us->generatePassword('password');
        $this->assertNotNull($passHash);

        $this->assertTrue($this->us->validatePassword('password', $passHash));
    }
}