<?php

use Gvera\Helpers\validation\ValidationService;
use Gvera\Models\User;
use Gvera\Models\UserRole;
use Doctrine\ORM\EntityRepository;
use Gvera\Helpers\session\Session;
use Gvera\Helpers\entities\GvEntityManager;
use PHPUnit\Framework\TestCase;

class UserServiceTest extends TestCase
{

    private $userService;
    /**
     * @test
     */
    private $user;
    /**
     * @var EntityRepository|\PHPUnit\Framework\MockObject\MockObject
     */
    private $repo;
    /**
     * @var GvEntityManager|\PHPUnit\Framework\MockObject\MockObject
     */
    private $gvEntityManager;

    /** @test */
    public function validateEmail()
    {
        $invalidEmail = 'test';
        $this->assertFalse($this->userService->validateEmail($invalidEmail));
        $validEmail = 'test@test.com';
        $this->assertTrue($this->userService->validateEmail($validEmail));
    }

    public function setUp():void
    {
        $this->repo = $this->createMock(EntityRepository::class);
        \Gvera\Helpers\locale\Locale::setCurrentLocale('en');

        $this->gvEntityManager = $this->createMock(GvEntityManager::class);
        $gvEntityManager = $this->gvEntityManager;
        $gvEntityManager->expects($this->any())
            ->method('getRepository')
            ->willReturn($this->repo);

        $session = $this->createMock(Session::class);
        $session->expects($this->any())
            ->method('set')
            ->with($this->isType('string'), $this->isType('array'))
            ->willReturn(true);

        $this->userService = new \Gvera\Services\UserService($gvEntityManager, $session, new ValidationService());

        $role = new UserRole();
        $role->setName("testRole");
        $role->setRolePriority(5);

        $user = new User();
        $user->setEmail("asd@aasd.com");
        $user->setUsername("test");
        $user->setRole($role);

        $this->user = $user;
        $passHash = $this->userService->generatePassword('test');
        $user->setPassword($passHash);



        $session->expects($this->any())
            ->method('get')
            ->with('user')
            ->willReturn(['role' => $role->getRolePriority(), 'username' => $user->getUsername()]);

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    /**
     * @test
     */
    public function generateAndValidatePassword()
    {
        $passHash = $this->userService->generatePassword('password');
        $this->assertNotNull($passHash);

        $this->assertTrue($this->userService->validatePassword('password', $passHash));
    }

    /**
     * @test
     */
    public function login()
    {
        $this->expectException(Exception::class);


        $user = new User();
        $user->setEmail("asd@aasd.com");
        $user->setUsername("test");
        $passHash = $this->userService->generatePassword('test');
        $user->setPassword($passHash);


        $repo = $this->createMock(EntityRepository::class);
        $repo->expects($this->any())
            ->method('findOneBy')
            ->willReturn($user);

        $gvEntityManager = $this->createMock(GvEntityManager::class);
        $gvEntityManager->expects($this->any())
            ->method('getRepository')
            ->willReturn($repo);

        $role = new UserRole();
        $role->setName("testRole");
        $role->setRolePriority(5);

        $user->setRole($role);

        $session = $this->createMock(Session::class);
        $session->expects($this->any())
            ->method('set')
            ->with($this->isType('string'), $this->isType('array'))
            ->willReturn(true);
        
        $session->expects($this->any())
            ->method('get')
            ->with('user')
            ->willReturn(['role' => $role->getRolePriority(), 'username' => $user->getUsername()]);
            

        $this->userService->entityManager = $gvEntityManager;
        $this->userService->session = $session;

        $this->userService->login($user->getUsername(), $passHash);
        $this->assertTrue($session->get('user')['username'] === $user->getUsername());
        $this->assertTrue($this->userService->getUserRole() === 5);
        $this->userService->login($user->getUsername(), 'failedpass');
    }

    /**
     * @test
     */
    public function logout()
    {
        $session = $this->createMock(Session::class);
        $session->expects($this->any())
            ->method('unsetByKey')
            ->with('user')
            ->willReturn(true);
        
        $session->expects($this->any())
            ->method('get')
            ->with('user')
            ->willReturn(null);

        $this->userService->session = $session;

        $this->userService->logout();

        $this->assertFalse($this->userService->isUserLoggedIn());
    }

    public function testUserAuthorization()
    {

        $roleAction = new \Gvera\Models\UserRoleAction();
        $roleAction->setActionName('test');

        $role = new UserRole();
        $role->setName("testRole");
        $role->setRolePriority(5);
        $role->addRoleAction($roleAction);

        $this->gvEntityManager->expects($this->any())->method('getRepository')
            ->willReturn($this->repo);

        $this->repo->expects($this->any())->method('findOneBy')
            ->willReturn($roleAction);

        $user = new User();
        $user->setEmail("asd@aasd.com");
        $user->setUsername("test");
        $user->setRole($role);


        $this->assertTrue($this->userService->userCan($user, 'test'));
        $this->assertFalse($this->userService->userCan(null, 'asd'));

    }
}