checks:
    php: true

build:
  nodes:
    my-tests:
      environment:
        php:
          version: 8.2
    analysis:
      environment:
        php:
          version: 8.2
      dependencies:
        after:
          - composer require --dev squizlabs/php_codesniffer:3.6
      tests:
        override:
          - php-scrutinizer-run