checks:
    php: true

build:
  nodes:
    my-tests:
      environment:
        php:
          version: 8.1
    analysis:
      environment:
        php:
          version: 8.1
      dependencies:
        after:
          - composer require --dev squizlabs/php_codesniffer:3.6
      tests:
        override:
          -
            command: phpcs-run
            use_website_config: false