checks:
    php: true

build:
  nodes:
    my-tests:
      environment:
        php:
          version: 7.3
    analysis:
      environment:
        php:
          version: 7.3
      dependencies:
        after:
          - composer require --dev squizlabs/php_codesniffer:2.9