version: "2"
services:
  nginx:
    image: nginx:latest
    ports:
    - 8089:80
    volumes:
    - .docker/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
    - php
  php:
    build: .docker/
    image: gv-docker
    expose:
    - 9000
    volumes:
    - .:/var/www/html
    - ./docker/config/php.ini:/usr/local/etc/php/php.ini
    environment:
      DB_HOST: mysql
      DB_DATABASE: gv
      DB_USERNAME: root
      DB_PASSWORD: root
      REDIS_HOST: redis
      SESSION_DRIVER: redis
      CACHE_DRIVER: redis
  mysql:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: gv
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
  redis:
    image: redis
    ports:
      - 16379:6379
