#!/bin/bash
#USE THESE SCRIPTS ONLY IF YOU ARE USING DOCKER.
# Exit when error
set -eo pipefail

GREEN='\033[1;32m'
RED='\033[1;31m'
GREY='\033[1;30m'
NC='\033[0m' # No Color

filenames=`ls ./shell/*`

if [ -z "$1" ]; then
    echo -e "${RED}No argument supplied, available commands: ${GREEN}"
    echo
    echo -e "${GREY}-/*-/*-/*-/*-/*-/*-/* APPLICATION COMMANDS -/*-/*-/*-/*-/*-/*-/*${GREEN}"
    for entry in $filenames; do
        if [ $entry != "./shell/migrations.yml" ]; then
            echo ${entry/"./shell/"}
        fi
    done
    echo "list-tasks"
    echo
    echo -e "${GREY}-/*-/*-/*-/*-/*-/*-/* DEPENDENCY COMMANDS -/*-/*-/*-/*-/*-/*-/* ${GREEN}"
    echo "composer"
    echo
    echo -e "${GREY}-/*-/*-/*-/*-/*-/*-/* BUILDING COMMANDS -/*-/*-/*-/*-/*-/*-/*${GREEN}"
    echo "build"
    echo "start"
    echo "enter"
    exit 1
fi

if [ $1 = "list-tasks" ]; then
    docker exec -t gv_php_1 sh -c "crontab -l"
    exit 1
fi

if [ $1 = "enter" ]; then
    docker exec -it "$2" /bin/bash
    exit 1
fi

if [ $1 = "build" ]; then
    docker-compose build && docker run --rm -v $(pwd):/app composer install
    exit 1
fi

if [ $1 = "composer" ]; then
    docker run --rm -v $(pwd):/app composer "$@"
fi

if [ $1 = "start" ]; then
    docker-compose up
    exit 1
fi

docker exec -it gv_php_1 php shell/"$@"
