#!/bin/bash
#USE THESE SCRIPTS ONLY IF YOU ARE USING DOCKER.
# Exit when error
set -eo pipefail

filenames=`ls ./shell/*`

if [ -z "$1" ]; then
    echo "No argument supplied, available commands:"
    for entry in $filenames; do
        if [ $entry != "./shell/migrations.yml" ]; then
            echo ${entry/"./shell/"}
        fi
    done
    echo "list-tasks"
    echo "build"
    echo "start"
    exit 1
fi

if [ $1 = "list-tasks" ]; then
    docker exec -t gv_php_1 sh -c "crontab -l"
    exit 1
fi

if [ $1 = "enter" ]; then
    docker exec -it "$2" /bin/bash
    exit 1
fi

if [ $1 = "build" ]; then
    docker-compose build && docker run --rm -v $(pwd):/app composer install
    exit 1
fi

if [ $1 = "composer" ]; then
    docker run --rm -v $(pwd):/app composer "$@"
fi

if [ $1 = "start" ]; then
    docker-compose up
    exit 1
fi

docker exec -it gv_php_1 php shell/"$@"
