logger:
  classPath: Monolog\
  objects:
    logger:
      class: Logger
      singleton: true
      arguments:
        "gv"

config:
  classPath: Gvera\Helpers\config\
  objects:
    config:
      class: Config
      singleton: true

http:
  classPath: Gvera\Helpers\http\
  objects:
    fileManager:
      class: FileManager
      arguments:
        "@config"
    httpRequest:
      class: HttpRequest
      singleton: true
      arguments:
        "@fileManager"
    httpResponse:
      class: HttpResponse
      singleton: true

email:
  classPath: Gvera\Helpers\email\
  objects:
    email:
      class: GvEmail

entities:
  classPath: Gvera\Helpers\entities\
  objects:
    entityManager:
      class: EntityManager
      singleton: true
      arguments:
        "@config"

dispatcher:
  classPath: Gvera\Helpers\events\
  objects:
    eventDispatcher:
      class: EventDispatcher
      singleton: true

services:
  classPath: Gvera\Services\
  objects:
    userService:
      class: UserService
      singleton: true
    forgotPasswordService:
      class: ForgotPasswordService
      arguments:
        "@entityManager"
    controllerService:
      class: ControllerService

commands:
    classPath: Gvera\Commands\
    objects:
      loginCommand:
        class: LoginCommand
        arguments:
          "@userService"

listeners:
  classPath: Gvera\Listeners\
  objects:
    userRegisteredEmailListener:
      class: UserRegisteredEmailListener
    throwableListener:
      class: ThrowableListener  

events:
  classPath: Gvera\Helpers\events\
  objects:
    eventListenerRegistry:
      class: EventListenerRegistry
      
