logger:
  classPath: Monolog\
  objects:
    logger:
      class: Logger
      singleton: true
      arguments:
        "gv"

session:
  classPath: Gvera\Helpers\session\
  objects:
    session:
      class: Session
      singleton: true

config:
  classPath: Gvera\Helpers\config\
  objects:
    config:
      class: Config
      singleton: true
      arguments: "/var/www/html/config/config.yml"

fileSystem:
  classPath: Gvera\Helpers\fileSystem\
  objects:
    fileManager:
      class: FileManager
      arguments: "@config"

http:
  classPath: Gvera\Helpers\http\
  objects:
    httpRequest:
      class: HttpRequest
      singleton: true
      arguments:
        - "@fileManager"
        - "@httpRequestValidator"
    httpResponse:
      class: HttpResponse
      singleton: true

email:
  classPath: Gvera\Helpers\email\
  objects:
    email:
      class: GvEmail

validation:
  classPath: Gvera\Helpers\validation\
  objects:
    validationService:
      class: ValidationService

entities:
  classPath: Gvera\Helpers\entities\
  objects:
    entityManager:
      class: GvEntityManager
      singleton: true
      arguments:
        - "@config"

dispatcher:
  classPath: Gvera\Helpers\events\
  objects:
    eventDispatcher:
      class: EventDispatcher
      singleton: true

services:
  classPath: Gvera\Services\
  objects:
    userService:
      class: UserService
      singleton: true
      arguments:
        - "@entityManager"
        - "@session"
        - "@validationService"
    forgotPasswordService:
      class: ForgotPasswordService
      arguments: "@entityManager"
    controllerService:
      class: ControllerService
    throttlingService:
      class: ThrottlingService
    basicAuthenticationService:
      class: BasicAuthenticationService
      arguments:
        - "@entityManager"
        - "@userService"
    jwtService:
      class: JWTService
      singleton: true


validators:
  classPath: Gvera\Helpers\http\
  objects:
    httpRequestValidator:
      class: HttpRequestValidator
      arguments: "@validationService"

routes:
  classPath: Gvera\Helpers\routes\
  objects:
    routeManager:
      class: RouteManager
      singleton: true
      arguments: "@httpRequest"

annotations:
  classPath: Gvera\Helpers\annotations\
  objects:
    annotationUtil:
      class: AnnotationUtil
      singleton: true

commands:
  classPath: Gvera\Commands\
  objects:
    loginCommand:
      class: LoginCommand
      arguments:
        - "@userService"
        - "@eventDispatcher"
    createNewUserCommand:
      class: CreateNewUserCommand
      arguments:
        - "@config"
        - "@entityManager"

listeners:
  classPath: Gvera\Listeners\
  objects:
    userRegisteredEmailListener:
      class: UserRegisteredEmailListener
      arguments: "@email"
    throwableListener:
      class: ThrowableListener
      arguments: "@logger"

security:
  classPath: Gvera\Helpers\security\
  objects:
    csrfFactory:
      class: CSRFFactory
      singleton: true
      
